import { createClient } from '@supabase/supabase-js';

export const SUPABASE_URL = 'https://rrwvhjcdgkwixxnqcfom.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyd3ZoamNkZ2t3aXh4bnFjZm9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ0MzQ1NDMsImV4cCI6MjA4MDAxMDU0M30.f1aGXUrNdQeVhrL-OoPKTJ7XOqb0N8PVo6dSEdhnHG4';

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

/* 
================================================================
DATABASE SETUP & MIGRATION INSTRUCTIONS
================================================================

IMPORTANT: If you encounter an error stating "Could not find the 'fileUrl' column",
please run the following SQL command in your Supabase SQL Editor to fix it:

   ALTER TABLE weeks ADD COLUMN IF NOT EXISTS "fileUrl" text;

================================================================
FULL SCHEMA SETUP
Copy and paste the following SQL into your Supabase SQL Editor 
and click "Run" to initialize all required tables.
================================================================

-- 1. Weeks Table (Stores Weekly Performance & Nested Pools)
create table if not exists weeks (
  id text primary key,
  title text,
  date text,
  "overallRoi" numeric,
  "fileUrl" text,
  pools jsonb, 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Fix for existing tables missing the column
alter table weeks add column if not exists "fileUrl" text;

-- 2. Picks Table (Stores Daily Edge Reports)
create table if not exists picks (
  id text primary key,
  title text,
  date text,
  content text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Summaries Table (Stores Game Recaps)
create table if not exists summaries (
  id text primary key,
  title text,
  date text,
  content text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Market Scans Table (Stores StatsEdge Scanner Data)
create table if not exists market_scans (
  id bigint generated by default as identity primary key,
  player text,
  stat text,
  line numeric,
  side text,
  book_odds numeric,
  dfs_implied numeric,
  ev numeric,
  best_platform text,
  scanned_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Visitor Emails (Marketing Gate)
create table if not exists visitor_emails (
  id uuid default uuid_generate_v4() primary key,
  email text not null,
  captured_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Enable Row Level Security (Optional: Open Access for Demo)
alter table weeks enable row level security;
alter table picks enable row level security;
alter table summaries enable row level security;
alter table market_scans enable row level security;
alter table visitor_emails enable row level security;

-- Create Policies (Allow Public Read/Write for Demo purposes)
create policy "Public Read Weeks" on weeks for select using (true);
create policy "Public Insert Weeks" on weeks for insert with check (true);
create policy "Public Update Weeks" on weeks for update using (true);
create policy "Public Delete Weeks" on weeks for delete using (true);

create policy "Public Read Picks" on picks for select using (true);
create policy "Public Insert Picks" on picks for insert with check (true);

create policy "Public Read Summaries" on summaries for select using (true);
create policy "Public Insert Summaries" on summaries for insert with check (true);

create policy "Public Read Scans" on market_scans for select using (true);
create policy "Public Insert Scans" on market_scans for insert with check (true);

create policy "Public Insert Emails" on visitor_emails for insert with check (true);

-- STORAGE SETUP:
-- 1. Go to "Storage" in Supabase Dashboard.
-- 2. Create a new public bucket named "reports".
-- 3. Add a policy to allow public uploads/reads if necessary.

*/