
import { createClient } from '@supabase/supabase-js';

export const SUPABASE_URL = 'https://rrwvhjcdgkwixxnqcfom.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyd3ZoamNkZ2t3aXh4bnFjZm9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ0MzQ1NDMsImV4cCI6MjA4MDAxMDU0M30.f1aGXUrNdQeVhrL-OoPKTJ7XOqb0N8PVo6dSEdhnHG4';

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

/* 
================================================================
DATABASE SETUP & MIGRATION INSTRUCTIONS
================================================================

1. FIX "COULD NOT FIND FILEURL COLUMN":
   Run this SQL in your Supabase SQL Editor to add the missing column:

   ALTER TABLE weeks ADD COLUMN IF NOT EXISTS "fileUrl" text;

2. STORAGE BUCKET SETUP (For PDF Reports):
   Run this SQL to create the storage bucket and allow public access:

   insert into storage.buckets (id, name, public) values ('reports', 'reports', true)
   on conflict (id) do nothing;

   create policy "Public Access" on storage.objects for select using ( bucket_id = 'reports' );
   create policy "Authenticated Upload" on storage.objects for insert with check ( bucket_id = 'reports' );

================================================================
FULL SCHEMA SETUP (Reference)
================================================================

-- 1. Weeks Table (Stores Weekly Performance & Nested Pools)
create table if not exists weeks (
  id text primary key,
  title text,
  date text,
  "overallRoi" numeric,
  "fileUrl" text,
  pools jsonb, 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Picks Table (Stores Daily Edge Reports)
create table if not exists picks (
  id text primary key,
  title text,
  date text,
  content text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Summaries Table (Stores Game Recaps)
create table if not exists summaries (
  id text primary key,
  title text,
  date text,
  content text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Market Scans Table (Stores StatsEdge Scanner Data)
create table if not exists market_scans (
  id bigint generated by default as identity primary key,
  player text,
  stat text,
  line numeric,
  side text,
  book_odds numeric,
  dfs_implied numeric,
  ev numeric,
  best_platform text,
  scanned_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Visitor Emails (Marketing Gate)
create table if not exists visitor_emails (
  id uuid default gen_random_uuid() primary key,
  email text not null,
  captured_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. User Bets (Client Portfolio Tracking)
create table if not exists user_bets (
  id uuid default gen_random_uuid() primary key,
  selection text not null,
  odds text not null,
  stake numeric not null,
  to_win numeric not null,
  status text default 'PENDING',
  pnl numeric default 0,
  market_type text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. Enable Row Level Security (Optional: Open Access for Demo)
alter table weeks enable row level security;
alter table picks enable row level security;
alter table summaries enable row level security;
alter table market_scans enable row level security;
alter table visitor_emails enable row level security;
alter table user_bets enable row level security;

-- Create Policies (Allow Public Read/Write for Demo purposes)
create policy "Public Read Weeks" on weeks for select using (true);
create policy "Public Insert Weeks" on weeks for insert with check (true);
create policy "Public Update Weeks" on weeks for update using (true);
create policy "Public Delete Weeks" on weeks for delete using (true);

create policy "Public Read Picks" on picks for select using (true);
create policy "Public Insert Picks" on picks for insert with check (true);

create policy "Public Read Summaries" on summaries for select using (true);
create policy "Public Insert Summaries" on summaries for insert with check (true);

create policy "Public Read Scans" on market_scans for select using (true);
create policy "Public Insert Scans" on market_scans for insert with check (true);

create policy "Public Insert Emails" on visitor_emails for insert with check (true);

create policy "Public Read Bets" on user_bets for select using (true);
create policy "Public Insert Bets" on user_bets for insert with check (true);
create policy "Public Update Bets" on user_bets for update using (true);

*/
